<a href="https://colab.research.google.com/github/amirNoori73/01-Deep-Learning/blob/main/First_Deep_Learning_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [ ]:
x = tf.constant([-1, -2, 0, 1, 2, 5, 7], dtype=float)
y = x * 3 -5

In [ ]:
y.numpy()

array([ -8., -11.,  -5.,  -2.,   1.,  10.,  16.], dtype=float32)

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(units=1, activation=None, input_shape=[1])
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.compile(optimizer='sgd', loss='mean_squared_error')
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 1)              │             2 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(x, y, batch_size=None ,epochs=1000)

Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 415ms/step - loss: 33.4381
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 27.1125
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 23.2722
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 20.8548
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 19.2547
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 18.1268
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 17.2742
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 16.5846
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 15.9939
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 15.4653
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 14.9777
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 14.5190
Epoch 13/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 14.0820
Epoch 14/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 13.6625
Epoch 15/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - lo

In [ ]:
x_test = tf.constant([5, 10, 15, 20, 25], dtype=float)
y_real = x_test * 3 - 5
print(y_real)
y_pred = model.predict(x_test)
print(y_pred)

tf.Tensor([10. 25. 40. 55. 70.], shape=(5,), dtype=float32)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step
[[10.000002]
 [24.999989]
 [39.999973]
 [54.999958]
 [69.99995 ]]


In [ ]:
y_real.shape

TensorShape([5])

In [ ]:
y_pred.shape

(5, 1)

In [ ]:
print(y_pred - tf.reshape(y_real, y_pred.shape))

tf.Tensor(
[[ 1.9073486e-06]
 [-1.1444092e-05]
 [-2.6702881e-05]
 [-4.1961670e-05]
 [-5.3405762e-05]], shape=(5, 1), dtype=float32)


In [ ]:
print(tf.reshape(y_pred, y_real.shape) - y_real)

tf.Tensor(
[ 1.9073486e-06 -1.1444092e-05 -2.6702881e-05 -4.1961670e-05
 -5.3405762e-05], shape=(5,), dtype=float32)
